### ISSUE TITLE
Time scale

### ISSUE THREAD

**Issue by zac-garby** [Zac-Garby/solar-system#1]
As said in the [README](https://github.com/Zac-Garby/solar-system/blob/master/README.md), it'd be quite nice for there to be a time scale, i.e. 1 year = 2 minutes.

The current game-time year (probably starting at 0AD) will increase with the time scale and be displayed somewhere. Also, maybe the orbital speed of planets could be adjusted to have around 0.5-5 revolutions per year?

**Comment by leoybkim** [comment]
I will take this!

**Comment by zac-garby** [comment]
Ahh, sorry I literally just started it...
