### ISSUE TITLE
Allow sliders to change value by clicking on the track

### ISSUE THREAD

**Issue by zac-garby** [Zac-Garby/solar-system#20]
At the moment, you can only move a slider's value by dragging the handle. Although it's only a small thing, it gets quite annoying when clicking along the track doesn't move the handle to the clicked position. This should be quite easy to fix.

**Comment by noideas4thisname** [comment]
I'll take this one.

**Comment by noideas4thisname** [comment]
PR #28 submitted

**Comment by zac-garby** [comment]
That fixed it
