### ISSUE TITLE
Add information on how to build and run the project

### ISSUE THREAD

**Issue by thecouchcoder** [Zac-Garby/solar-system#24]

**Comment by zac-garby** [comment]
Yeah, definitely. Really, the only reason I haven't done that is I didn't anticipate so many people wanting to use it.

**Comment by 0x72D0** [comment]
I think I can add the compilation step for linux

**Comment by zac-garby** [comment]
I'm out at the moment, but I'll add some info for compiling on Mac later.

**Comment by hanneskaeufler** [comment]
Compiling on my mac (which has Xcode, homebrew, cmake already) was a matter of

```
brew install sfml
cmake .
make
```

**Comment by AleCamara** [comment]
Sorry guys, completely missed this issue and already wrote something for MacOS.
@Zac-Garby feel free to discard the PR I sent if you have something already written.

**Comment by zac-garby** [comment]
@SoyYuma It's cool - I hadn't actually started writing it yet :)

**Comment by zac-garby** [comment]
I added a `Building` section to the README, so all that's left for this issue is Windows build instructions, I guess - but I'll close it for now.
