### ISSUE TITLE
There's no visual indication of which planet is currently selected

### ISSUE THREAD

**Issue by AleCamara** [Zac-Garby/solar-system#35]
ATM it's unclear which planet you have selected. Adding a simple border around the selected planet would be enough to make a huge UX difference :)

Dips on this if @Zac-Garby is happy with the change.

**Comment by zac-garby** [comment]
Nice idea. I'm thinking maybe a white / coloured border around the selected planet?

**Comment by AleCamara** [comment]
That's exactly what I was thinking of. IIRC SFML allows you to specify discontinuous borders? I'll play around a bit and come back with a screenshot of what I think it's the best, so you can comment.

**Comment by zac-garby** [comment]
Sounds good :)

**Comment by AleCamara** [comment]
I've added a simple continuous border with the same colour of the planet. Check green planet in the screenshot below.

![image](https://user-images.githubusercontent.com/1842070/31589380-6bcabdaa-b1f8-11e7-99cd-23cf453a7799.png)

What do you think about it?

I quickly explored the option to have a dashed border, but for that we need to resort to sf::VertexArray with sf::PrimitiveType::Lines, which is a bit of overkill for the border when the continuous line seems to work IMO.

**Comment by zac-garby** [comment]
I like it :) and yeah, I agree a dashed border would be overkill
