### ISSUE TITLE
Planets often die *way* too quickly

### ISSUE THREAD

**Issue by zac-garby** [Zac-Garby/solar-system#46]
In a lot of instances, the entire population dies before even the first day has ended. I know the point in the game is to keep the planets alive for as long as possible, so they must have to die *at some point*, but could someone have a go at changing some parameters to try and make them retain their populations for a bit longer?

**Comment by neilkakkar** [comment]
I think I fixed this while meddling with the population and food rates. Sending in a PR, have a look.
